name: 'ECR Lifecycle Cleaner Action'
description:
  'A GitHub Action for managing lifecycle policies and cleaning up orphaned
  images in AWS ECR.'
author: 'Gjorgji J.'

branding:
  icon: 'trash-2'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
