name: 'ECR Lifecycle Cleaner Action'
description:
  'A GitHub Action for managing lifecycle policies and cleaning up orphaned
  images in AWS ECR.'
author: 'Gjorgji J.'

branding:
  icon: 'trash-2'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  ecr-lifecycle-cleaner-version:
    description:
      'The version of the ECR Lifecycle Cleaner CLI to use. (e.g. 1.2.1)'
    required: true
  command:
    description: 'The ECR Lifecycle Cleaner command to run and its arguments.'
    required: false
    default: 'clean --allRepos --dryRun'

# outputs:
#   time:
#     description: Your output description here

runs:
  using: node20
  main: dist/index.js
